[tool.ruff]

line-length = 200

lint.select = ["I", "N", "E", "F"]
lint.ignore = ["E402", "F403"]

exclude = [
    ".git",
    ".ruff_cache",
    ".vscode",
    ".github",
    "k8s",
    "__init__.py",
    "/**/migrations/*.py"
]