# Generated by Django 5.0 on 2024-06-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('data', models.CharField(max_length=4, verbose_name='ヘルスチェック')),
            ],
        ),
    ]
