# Generated by Django 5.0 on 2024-06-21 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('title', models.CharField(max_length=255, verbose_name='謎解きのタイトル')),
                ('image', models.TextField(blank=True, null=True, verbose_name='謎解きのサムネイル')),
                ('status', models.IntegerField(choices=[(0, '下書き'), (1, '申請中'), (2, '公開中')], verbose_name='ステータス')),
                ('mystery', models.TextField(blank=True, null=True, verbose_name='問題文の番号')),
                ('complete_msg', models.TextField(blank=True, null=True, verbose_name='完了メッセージ')),
                ('complete_count', models.IntegerField(verbose_name='謎解きをクリアされた回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('published_at', models.DateTimeField(verbose_name='公開日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('title', models.CharField(max_length=255, verbose_name='問題文のタイトル')),
                ('description', models.TextField(verbose_name='問題文の詳細')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='問題文のヒント')),
                ('correct_assets', models.TextField(blank=True, null=True, verbose_name='正解時のアセット')),
                ('incorrect_assets', models.TextField(blank=True, null=True, verbose_name='不正解時のアセット')),
                ('correct_msg', models.TextField(blank=True, null=True, verbose_name='正解時のメッセージ')),
                ('incorrect_msg', models.TextField(blank=True, null=True, verbose_name='不正解時のメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('mystery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.mystery', verbose_name='謎解きID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
