# Generated by Django 5.0 on 2024-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0002_rename_user_id_mystery_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystery',
            name='complete_count',
            field=models.IntegerField(default=0, verbose_name='謎解きをクリアされた回数'),
        ),
        migrations.AlterField(
            model_name='mystery',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開日時'),
        ),
    ]
