# Generated by Django 5.0 on 2024-06-26 17:03

import mystery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0003_alter_mystery_complete_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mystery.models.upload_to, verbose_name='謎解きのサムネイル'),
        ),
    ]
