# Generated by Django 5.0 on 2024-06-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0004_alter_mystery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_assets',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_assets',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_msg',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_model',
            field=models.TextField(blank=True, null=True, verbose_name='正解時に出現するモデル'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_model_attributes',
            field=models.TextField(blank=True, null=True, verbose_name='正解時に出現するモデルのattributes'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_vps',
            field=models.TextField(blank=True, null=True, verbose_name='正解時のVPS'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_vps_attributes',
            field=models.TextField(blank=True, null=True, verbose_name='正解時のVPSのattribute'),
        ),
    ]
