# Generated by Django 5.0 on 2024-06-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0005_remove_question_correct_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_msg_attributes',
            field=models.TextField(blank=True, null=True, verbose_name='正解時のメッセージのattribute'),
        ),
    ]
