# Generated by Django 5.0 on 2024-06-28 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0006_question_correct_msg_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMysteryStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('status', models.TextField(blank=True, null=True, verbose_name='ユーザの謎解きのステータス')),
                ('mystery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystery.mystery', verbose_name='謎解きID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
