# Generated by Django 5.0 on 2024-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystery', '0007_usermysterystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_game',
            field=models.TextField(blank=True, null=True, verbose_name='正解時に出現するゲーム'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_game_attributes',
            field=models.TextField(blank=True, null=True, verbose_name='正解時に出現するゲームのattributes'),
        ),
    ]
