# Generated by Django 5.0 on 2024-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='画面に表示するタイトル')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='GLBとpngのファイル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Vps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('vps_name', models.CharField(max_length=255, unique=True, verbose_name='VPSのLocation Name')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='画面に表示するタイトル')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='GLBとpngのファイル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
