# Generated by Django 5.0 on 2024-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='actions',
            field=models.TextField(blank=True, null=True, verbose_name='glbのアクションの種類'),
        ),
    ]
