name: Test

on:   
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - stg
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setup mysql-action
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 
          container port: 3306 
          character set server: 'utf8' 
          collation server: 'utf8_general_ci' 
          mysql version: '8.2.0' 
          mysql database: 'test_yakiniku-hackathon' 
          mysql root password: 'root'
          mysql user: 'user'
          mysql password: 'password'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Python linter
        run: ruff ./
      - name: test
        run: |
          python manage.py test --settings=config.settings.test
        continue-on-error: false